# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import room.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('avatar', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=room.models.upload_to)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_participants', models.PositiveSmallIntegerField(default=2)),
                ('date_time_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_time_end', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_string', models.CharField(max_length=30)),
                ('expired', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('full', models.BooleanField(default=False)),
                ('welcome', models.TextField(blank=True, null=True)),
                ('reward', models.TextField(blank=True, null=True)),
                ('expense', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdvancedRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='room.Room')),
                ('options', models.TextField(blank=True, null=True)),
                ('apply', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=('room.room',),
        ),
    ]
