# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
        ('other', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='other.Label'),
        ),
        migrations.AddField(
            model_name='room',
            name='marked_users',
            field=models.ManyToManyField(blank=True, related_name='marked_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.ManyToManyField(related_name='joined_rooms', through='room.Participance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='title_labels',
            field=models.ManyToManyField(blank=True, to='other.TitleLabel'),
        ),
        migrations.AddField(
            model_name='participance',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
        ),
        migrations.AddField(
            model_name='participance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participance',
            unique_together=set([('room', 'user')]),
        ),
        migrations.AddField(
            model_name='advancedroom',
            name='advertising',
            field=models.ManyToManyField(related_name='advanced_rooms', to='other.University'),
        ),
    ]
