# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20170313_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_participants',
            field=models.PositiveSmallIntegerField(default=2, null=True),
        ),
    ]
