# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20170315_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='avatar',
            new_name='cover',
        ),
    ]
