# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostthumbdown',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostthumbup',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participantthumbdown',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantthumbup',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
